services:
  mongodb:
    image: mongo:4.4
    restart: always
    env_file:
      - "./app/.env"
    expose:
      - 27017
    volumes:
      - ./db_data/db:/data/db
  
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    env_file:
      - "./app/.env"
