from decouple import config

TELEGRAM_API_ID = config("TELEGRAM_API_ID", cast=int)
TELEGRAM_API_HASH = config("TELEGRAM_API_HASH")
TELEGRAM_BOT_TOKEN = config("TELEGRAM_BOT_TOKEN")

MONGO_USERNAME = config("MONGO_INITDB_ROOT_USERNAME")
MONGO_PASSWORD = config("MONGO_INITDB_ROOT_PASSWORD")